# Example configuration for the SSH Relay.
#
# Example usage:
#   $ bazel run //relay/cmd:ssh_relay -- --logtostderr \
#     --config=$(bazel info workspace)/examples/ssh-relay.textproto

server_options {
  # Optionally listen on a specific address, defaults to the unspecified address.
  addr: "127.0.1.1"

  # Specify a custom port, defaults to 8022.
  port: "8022"

  # Inbound SSL/TLS settings.
  tls_config {
    # SSL (in PEM format).
    cert_file: "/etc/ssh-relay/ssh-relay.crt"
    key_file: "/etc/ssh-relay/ssh-relay.key"

    # Root CA certificate to use for validating client certs.
    client_ca_certs: "/etc/ssh-relay/ca.crt"

    # Require valid client certs.
    client_auth_type: REQUIRE_AND_VERIFY_CLIENT_CERT
  }
}

client_options {
  dial_timeout { seconds: 3 }
}

# Limit SSH sessions to 24 hours.
max_session_age { seconds: 86400 }

origin_cookie_name: "o"
